### ISSUE TITLE
I found a more complete map

### ISSUE THREAD

**Issue by Chikaze** [SirJimmothy/phasmo#1]
https://github.com/SirJimmothy/phasmo/blob/a26783611570ce9c00e51fd51fcf327fa7c1f0ef/phasmo.js#L232
https://github.com/SirJimmothy/phasmo/blob/gh-pages/img/map_prison.png

**I found a more complete map**
https://steamsplay.com/phasmophobia-map-location-on-how-to-find-ghost-quickly/

https://steamsplay.com/wp-content/uploads/2021/08/Phasmophobia-Map-Location-on-How-to-Find-Ghost-Quickly-Prison-7A1CB4A-steamsplay-com.jpg

**Comment by SirJimmothy** [comment]
Updated, thanks!
