### ISSUE TITLE
obake useful add

### ISSUE THREAD

**Issue by Chikaze** [SirJimmothy/phasmo#2]
"obake": {
		"name":					"Obake",
		"clues":				['emf','orb','prints'],
		"useful":				[
			"Leaves few traces during interactions",
			"Can shapeshift",
			"Has an additional 6-finger fingerprint",
		],
	},
![image](https://user-images.githubusercontent.com/5087866/139332541-77c7197c-56c5-4094-8b5e-2ef2ec6d660f.png)

**Comment by SirJimmothy** [comment]
Updated
