### ISSUE TITLE
Sorry for my English

### ISSUE THREAD

**Issue by Chikaze** [SirJimmothy/phasmo#3]
49.

	"jinn": {
		"name":					"Jinn",
		"clues":				['emf','prints','temps'],
		"useful":				[
			"With breaker on, will be fast unless within 4m of target",
			"Will not turn off breaker",
			//"Chance to drop sanity by 25% within 3m",
			+"turn on breaker, drop 25% sanity when there is ghost within 3m.",
		],
	},

75.

	"obake": {
		"name":					"Obake",
		"clues":				['emf','orb','prints'],
		"useful":				[
			//"Leaves few traces during interactions",
			"Can leave 6-finger fingerprints",
			"-25% chance to leave fingerprints",
			"Fingerprints can disappear after 30s",
			"Nightmare mode: fingerprints are guaranteed",
		],
	},

86.

	"oni": {
		"name":					"Oni",
		"clues":				['emf','dots','temps'],
		"useful":				[
			"More active with >1 people in room",
			//"Can throw items at high speed",
			+"Can throw items to more distant places",
		],
	},

94.

	"onryo": {
		"name":					"Onryo",
		"clues":				['box','orb','temps'],
		"useful":				[
			"Can hunt above 50% sanity without flame in room",
			"Lit candles act as crucifixes; 3M hunt blocking range",
			+"Extinguishing last room flame can trigger hunts",
		],
	},

120.

	"raiju": {
		"name":					"Raiju",
		"clues":				['dots','emf','orb'],
		"useful":				[
			//"Drains power during hunts to gain speed",
			+"presence of electronic devices nearby will Increased movement speed",
			+"presence of electronic devices nearby will can hunt at 70% sanity",
		],
	},

135.

	"shade": {
		"name":					"Shade",
		"clues":				['emf','temps','writing'],
		"useful":				[
			//"Won't try to hunt with &gt;1 person in room",
			+"Won't try to hunt with Someone's in a room",
			+"Reduced signs of activity with &gt;2 person in room",
		],
	},

157.

	"wraith": {
		"name":					"Wraith",
		"clues":				['box','emf','dots'],
		"useful":				[
			"When loud-stepping after salt, no footprints show",
			"After stepping in salt, becomes permanently more active",
			//"Can teleport to random indoor player",
			+"can be teleported to place 3 meters near a random player and leave EMF5 evidence",
		],
	},

174.

	"yurei": {
		"name":					"Yurei",
		"clues":				['orb','dots','temps'],
		"useful":				[
			//"Sanity drops 2x within 10m while visible / hunting",
			"Chance to drop sanity by 14% within 3m",
			//"Cannot roam while smudged",
			+"smudged will interrupt wandering",
			+"smudged will reduce signs of activity",
		],
	}
};

**Comment by SirJimmothy** [comment]
Thanks - updating the helpful info, with the following exceptions:

#86: Developers confirmed to Insym that it's high speed throws, not necessarily further throws
#94: Developers confirmed to Insym that candles act like crucifixes to an onryo
#135: Citation for this change?
#174: Existing wording already adequately covers the described behaviour

**Comment by Chikaze** [comment]
#86: high speed is a gravitational acceleration in the program
#94: but when the flame is extinguished, it will be easier to enter the hunting state
#135: proof in the case that my friend made the ghost appear permanently by illegal means
#174: Sorry for my English comprehension

**Comment by SirJimmothy** [comment]
#86: Throws can happen in multiple directions; high speed is the best way to describe it, and you can identify by sound
#94: I believe "crucifix behaviour" covers this description well - I may need to add a "regular hints" section that covers standard gameplay elements such as crucifixes
#135 It's possible this happened just outside a room's border; the established behaviour is confirmed

I'm going to close here, but thanks for your input =]
