### ISSUE TITLE
Change suggestion: Spirit

### ISSUE THREAD

**Issue by TotenKnopf** [SirJimmothy/phasmo#37]
#### Change suggestion: Spirit 
Text edits

currently:
>Incense lasts twice as long: 180s

add line: 
>Spirits cannot step in salt

**Comment by SirJimmothy** [comment]
Do you have a citation for this? I can't find any supporting notes for this.

Thanks

**Comment by TotenKnopf** [comment]
sorry, my transation tricked me there... 
your notes are correct, the salt fact belongt to Wraith
