### ISSUE TITLE
Christmas update

### ISSUE THREAD

**Issue by Chikaze** [SirJimmothy/phasmo#4]
"banshee": {
		"name":					"Banshee",
		"clues":				['dots','prints','orb'],
		"useful":				[
			"Crucifixes have +2m range",
			//"Can hunt at any sanity level",
			"Hunts only its target, unless target is outside",
			"Can teleport to target at start of hunt, if they had ghost LoS within 20s",
		],
	},
	"demon": {
		"name":					"Demon",
		"clues":				['prints','temps','writing'],
		"useful":				[
			++"20% chance to hunt at any sanity level"
			"Can hunt at 70% sanity",
			"Successful ouija board questions cost no extra sanity",
		],
	},

	"onryo": {
		"name":					"Onryo",
		"clues":				['box','orb','temps'],
		"useful":				[
			++"Can hunt above 60% sanity without flame in room",
			++(20% for other ghosts)"40% Chance to hunt when flame is extinguished",
			//(All ghosts have this characteristic)"The more dead players, the higher hunt chance when flame extinguished",
			++"At sanity &gt;40% , Flames act as crucifixes and extinguish it",
			//"When flame prevents hunt, it is blown out",
		],

**Comment by SirJimmothy** [comment]
Do you have citations for these changes - I'd like to make sure I know as much as I can about these too

**Comment by Chikaze** [comment]
Fandom

Parameter values (read-out value) are from CE+xdbg

**Comment by SirJimmothy** [comment]
Banshee hunt mechanic moved to Demon

Can't find citation for all ghosts hunt chance after flame extinguishing

Other changes implemented
