### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by DrTobogganMD** [SirJimmothy/phasmo#5]
Demon
Demons have had their weakness replaced with the Banshee’s, as it is more thematical and serves as a better counter to their strength
Crucifixes will stop a hunt starting within 5m instead of 3m

Banshee
Banshee has received a new weakness and new abilities
Weakness: Banshees can sometimes be heard wailing with a parabolic microphone
The Banshee’s paranormal sound has been improved
Singing ghost events will now drain an extra 5% sanity on the Banshee's target
Banshees will only check their targets sanity % for initiating a hunt in multiplayer
Banshees will often wander toward their target when roaming

Mare
Fixed an issue where you could spam light switches to force the Mare’s ability

Shade
We've found that some Shades are particularly fond of showing themselves early on in contracts, so we've dialled them back a bit to avoid confusion with other ghosts:
Shades will have a much lower chance to perform ghost events, returning to normal as average player sanity decreases
For every 1% of average sanity lost, ghost event chance is increased by 2% (capped at 100%), for example:
100% average sanity = 0% chance
75% average sanity = 50% chance
50% average sanity = 100% chance

Poltergeist
Poltergeist’s ability will now reduce the sanity of all players around the ghost instead of just one player
2% sanity drain per object thrown

Hantu
Hantu have become the new ghost people love to loop, which is great. However, they weren't threatening when they should be! So we've given them some speed and ability changes to make them a bit more frightening in the cold.
Hantu now have double the chance to turn off the power
Hantu will now show their breath in room temperatures of 3°C or lower
Hantu maximum speed has been increased, and will change speed between smaller temperature brackets
1.4 m/s= 15°C+
1.5 m/s= 12°C
1.65 m/s= 9°C
1.8 m/s= 6°C
2.2 m/s= 3°C
2.5 m/s= 0°C

‘The High Priestess’ tarot card has received new functionality, which should help with drawing one early, playing solo and to counter some of the risk involved with other cards
Drawing this card when no one is dead will revive the next player who dies

‘The Tower’ card and Voodoo Doll pins can now force the ghost to interact with the Ghost Writing Book, DOTS Projector and doors, instead of only interacting with clutter
Voodoo Doll’s sanity drain has been reduced
Heart pin from 20% to 10%

**Comment by SirJimmothy** [comment]
Thanks; this format is perfect for getting through the updates quickly

**Comment by DrTobogganMD** [comment]
You're welcome. A number of bugfixes too but these where the items that affected the tool :D
