### ISSUE TITLE
3 March Update

### ISSUE THREAD

**Issue by DrTobogganMD** [SirJimmothy/phasmo#7]
Hantu has received further hunt speed changes
- 1.4 m/s = 15°C+
- 1.75 m/s = 12°C
- 2.1 m/s = 9°C
- 2.3 m/s = 6°C
- 2.5 m/s = 3°C
- 2.7 m/s = 0°C

Other changes are bugfixes and not relevant for the tool.

**Comment by SirJimmothy** [comment]
When you say 2.1 speed etc, do you mean 2.1x player speed or 2.1 m/s?

**Comment by DrTobogganMD** [comment]
Sorry, all speed values are in m/s. I've updated the original issue.
