### ISSUE TITLE
other langs translation

### ISSUE THREAD

**Issue by VelikiySebas** [SirJimmothy/phasmo#8]
can you add russian or/and ukrainian lang? i want to help you with translation

**Comment by SirJimmothy** [comment]
Sure, I'll put this on the list - I'll have to build a language file out and add a selector, so give me some time.

**Comment by VelikiySebas** [comment]
> 

okay so Ill wait for updates and maybe pull russian for you, I dont remember how its work on github

**Comment by SirJimmothy** [comment]
I'm looking at which strings to change for different languages, and I'm hoping you can help:

Do the names of the maps change in other languages, or are they always the same names?

**Comment by VelikiySebas** [comment]
names of the maps same in all languages, changes ghost names, utilities and other info about ghosts etc

**Comment by SirJimmothy** [comment]
Language support is now in place; instructions are at the bottom of the readme - you can just push the language file and I'll modify the main document as required
